### ISSUE TITLE
Return Tool ID and/or Agent ID in the Blocks API request

### ISSUE THREAD

**Issue by Johntyb** [AgentHQ/development#10]
GET agents/{agent_id}/block

Also be good to have the desciptions.

**Comment by bborn** [comment]
@Johntyb can you show me an example so I can understand what you're doing here? 

To clarify: 

An Agent has man Blocks. A Block belongs to an Agent and a Blockable, which can be an Agent, Tool, or DocumentIndex (specified by the `blockable_type` attr.

Are you saying you just want the `blockable_id` returned in the request?

**Comment by Johntyb** [comment]
![image](https://user-images.githubusercontent.com/3426135/221428404-92f809ac-4d3e-4bb8-aab4-438bdf09b451.png)
There are lots of blocks, yes and they all have block ID's. But I want to display the title, and the descript of the tool or agent they refer to. There is no way, that I can currently see of cross referencing to the tools.
![image](https://user-images.githubusercontent.com/3426135/221428509-bc21d355-6c89-47d5-bb7d-6271890af5bc.png)
The tools have their own unique ID's, that arent same as the blockable_id

**Comment by Johntyb** [comment]
@bborn Just realised the blockable_id **is** the id of the tool or agent....durr. Sorry.

**Comment by bborn** [comment]
Right! So you can use the `blockable_id` and `blockable_type` to lookup whatever the tool/agent/index is.

**Comment by bborn** [comment]
Although I could be convinced to just include it in the /agent/ID response
