### ISSUE TITLE
connect to external vector stores

### ISSUE THREAD

**Issue by bborn** [AgentHQ/development#13]

**Comment by ubuntudroid** [comment]
Or for the time being at least the option to modify the existing internal ones? And maybe a few more internal ones like `GPTChromaIndex`? 😅

**Comment by bborn** [comment]
@ubuntudroid ok, I'm starting with adding the Pinecone vector store, so you can either initialize the index in AGHQ and we'll create the index in Pinecone, or you can pass in an existing Pinecone index and we'll pull from it.

I can see adding other external stores (Weviate, Postgres, etc.), but can you explain why you want other internal ones like Chroma? Not sure what difference it really makes on your end if the index is being stored on AGHQ anyway. Thanks

**Comment by ubuntudroid** [comment]
@bborn No difference, I just thought it might be easier (= quicker) to do for you than connecting external ones.
