### ISSUE TITLE
Customization of document index prompts

### ISSUE THREAD

**Issue by ubuntudroid** [AgentHQ/development#14]
Right now, it isn't possible to change the prompts for document indexes.

Data in different document indexes can vary heavily in structure, format, and the index's responses potentially need to adapt to the requirements of the requesting agent. Therefore, it would make sense to be able to modify the prompt for document index LLMs as well.

I had very good results in langchain with document index (over there that would be tools backed up by a vector store) prompt optimizations.

**Comment by bborn** [comment]
Initial support for this is live:

Document Indexes now allow passing a custom qa template: https://agent-hq.notion.site/Document-Indexes-347beefb3b6845a78e171138c3a77562#487c0e82e12742ed95920ba2da97a0f5

Example: https://d.pr/i/TKqjxT, example response: https://d.pr/i/QSusb8

@ubuntudroid  let me know what you think.

**Comment by ubuntudroid** [comment]
Looks great, thanks @bborn! 🚀
